apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployments
  labels:
    env: prod
    app: main
    tier: backend
    owner: alex
spec:
  selector:
    matchLabels:
      project: pro
  template:
    metadata:
      labels:
        project: pro
    spec:
      containers:
        - name: asshole
          image: nelson9291/k8s-example:latest
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployments
  maxReplicas: 6
  minReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80



